# Generated by Django 3.0.8 on 2020-08-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-views',)},
        ),
    ]
